// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Retail.Data.SqlDb.EfModels.Models
{
    public partial class OrderLineItem
    {
        [Key]
        public int LineItemId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal UnitPrice { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal TotalPrice { get; set; }

        [ForeignKey(nameof(OrderId))]
        [InverseProperty("OrderLineItems")]
        public virtual Order Order { get; set; }
        [ForeignKey(nameof(ProductId))]
        [InverseProperty("OrderLineItems")]
        public virtual Product Product { get; set; }
    }
}