// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Retail.Data.SqlDb.EfModels.Models
{
    public partial class Product
    {
        public Product()
        {
            OrderLineItems = new HashSet<OrderLineItem>();
        }

        [Key]
        public int ProductId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductName { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Price { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? SalesPrice { get; set; }

        [InverseProperty(nameof(OrderLineItem.Product))]
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
    }
}